# Generated by Django 2.2.8 on 2020-01-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callrequest',
            options={'verbose_name': 'Заявку', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страну', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Вакансию', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AddField(
            model_name='vacancy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vacancy_images', verbose_name='Фото вакансии'),
        ),
        migrations.AlterField(
            model_name='callrequest',
            name='call_back',
            field=models.BooleanField(default=False, verbose_name='Перезвонил'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='age',
            field=models.CharField(max_length=100, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужчины'), ('female', 'Женщины'), ('male/female', 'Мужчины/Женщины')], default='male', max_length=100, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.FloatField(verbose_name='Зарплата'),
        ),
    ]
