# Generated by Django 2.2.8 on 2020-01-25 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_auto_20200125_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='vacancy.Country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='gender',
            field=models.CharField(choices=[('Мужчины', 'Мужчины'), ('Женщины', 'Женщины'), ('Мужчины/Женщины', 'Мужчины/Женщины')], default='Мужчины', max_length=100, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.CharField(max_length=100, verbose_name='Зарплата'),
        ),
    ]
